=== sakorepanov/xml-stax-jaxb-homework/src/main/resources/item-good-test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="sameUri" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="color"/>
              <xs:element type="xs:string" name="manufacturer"/>
              <xs:element type="xs:string" name="model"/>
              <xs:element name="date">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[0-3][0-9]-[01][0-9]-[0-9]{4}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="xs:float" name="price"/>
              <xs:element type="xs:byte" name="quantity"/>
              <xs:element type="xs:string" name="subcategory"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="category"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sakorepanov/xml-stax-jaxb-homework/src/main/resources/item-good-test.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<items xmlns="file://C:/Users/Sergei_Korepanov2/IdeaProjects/xml-stax-jaxb-homework/src/main/resources/item-good-test.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="file://C:/Users/Sergei_Korepanov2/IdeaProjects/xml-stax-jaxb-homework/src/main/resources/item-good-test.xsd ">
    <category>Comps</category>
    <color>Black</color>
    <manufacturer>HP</manufacturer>
    <model>HHH</model>
    <price>4000.0</price>
    <quantity>5</quantity>
    <subcategory>Monitors</subcategory>
</items>
